# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt28th_iOS_Assignment_1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'TextFieldEffects'
  # Pods for Sopt28th_iOS_Assignment_1

end
